// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:category": {
    params: {
      "category": string;
    };
  };
  "/:category/:id/:item": {
    params: {
      "category": string;
      "id": string;
      "item": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/:category" | "/:category/:id/:item";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$category.jsx": {
    id: "routes/$category";
    page: "/:category";
  };
  "routes/$category.$id.$item.jsx": {
    id: "routes/$category.$id.$item";
    page: "/:category/:id/:item";
  };
};